### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by louisfrederic** [proto3/pywing#1]
It seams that there ocourse a error in the graphicview.py.
this is the output:
`(my-venv) C:\Users\frederic.louis\Documents\Privat\Foam_CNC\Sofware\pywing-master>py pywing.py
Traceback (most recent call last):
  File "pywing.py", line 386, in <module>
    gview = GraphicView(cut_proc, machine)
  File "C:\Users\frederic.louis\Documents\Privat\Foam_CNC\Sofware\pywing-master\graphicview.py", line 75, in __init__
    self.plot_l = scene.LinePlot(width=2.0, color=(0.91, 0.31, 0.22, 1.0), parent=self.view.scene)
  File "C:\my-venv\lib\site-packages\vispy\scene\visuals.py", line 127, in __init__
    subclass.__init__(self, *args, **kwargs)
  File "C:\my-venv\lib\site-packages\vispy\visuals\line_plot.py", line 70, in __init__
    edge_width=edge_width, connect=connect)
  File "C:\my-venv\lib\site-packages\vispy\visuals\line_plot.py", line 126, in set_data
    self._markers.set_data(pos=pos, **marker_kwargs)
  File "C:\my-venv\lib\site-packages\vispy\visuals\markers.py", line 538, in set_data
    pos.ndim == 2 and pos.shape[1] in (2, 3))
AssertionError`

**Comment by reederward1285** [comment]
This is an issue with vispy, which was fixed in 0.6.2. Install this new version by running ```pip3 install vispy==0.6.2```
I have made a pull request to update requirements.txt accordingly.
